version: "3"

services:
  web:
    image: backend-image
    container_name: web
    hostname: web
    build: .
    command: sh -c "python insu-bro-nce/manage.py compilemessages &&
                    wait-for-it --parallel --service postgres:5432 --service elasticsearch:9200 &&
                    python insu-bro-nce/manage.py migrate &&
                    python insu-bro-nce/manage.py loaddata fixtures.json &&
                    wait-for-it --parallel --service rabbit:5672 --service mongo:27017 &&
                    python insu-bro-nce/manage.py runserver 0.0.0.0:8080"
    env_file: dev.env
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbit
      - mongo
      - elasticsearch

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    hostname: postgres
    env_file: dev.env
    ports:
      - "5432:5432"

  # TODO: на версии 3.9.0 не работают переменные. Нужен конфигурационный файл
  rabbit:
    image: rabbitmq:3.8.19-management
    restart: on-failure
    container_name: rabbit
    hostname: rabbit
    env_file: dev.env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    image: backend-image
    container_name: celery
    restart: on-failure
    command: sh -c "wait-for-it --service web:8080 &&
                    cd insu-bro-nce && celery -A config worker -l INFO"
    depends_on:
      - web
      - rabbit

  mongo:
    image: mongo:5.0.2
    restart: on-failure
    container_name: mongo
    hostname: mongo
    env_file: dev.env
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:7.14.0
    restart: on-failure
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
