version: "3"

services:
  web:
    build: .
    command: bash -c "python insu-bro-nce/manage.py migrate && django-admin compilemessages && python insu-bro-nce/manage.py runserver 0.0.0.0:8080"
    env_file: dev.env
    volumes:
      - .:/code
    ports:
      - "8080:8080"
