# Generated by Django 3.2.5 on 2021-07-18 17:22

from django.db import migrations


CATEGORY_NAMES = (
    'ОСАГО',
    'КАСКО',
    'Здоровье',
    'Недвижимость',
    'Бизнес',
)


def apply_migration(apps, schema_editor):
    InsuranceProductCategory = apps.get_model(
        'insurance', 'InsuranceProductCategory')
    InsuranceProductCategory.objects.bulk_create((
        InsuranceProductCategory(name=name) for name in CATEGORY_NAMES
    ))


def revert_migration(apps, schema_editor):
    InsuranceProductCategory = apps.get_model(
        'insurance', 'InsuranceProductCategory')
    InsuranceProductCategory.objects.filter(name__in=CATEGORY_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
