# Generated by Django 3.2.5 on 2021-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_hardcoded_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='insuranceproductcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
