# Generated by Django 3.2.5 on 2021-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_add_is_active_field_to_insurance_product_and_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceproduct',
            options={'ordering': ('-created_at',), 'verbose_name': 'insurance product', 'verbose_name_plural': 'insurance products'},
        ),
        migrations.AlterModelOptions(
            name='insuranceproductcategory',
            options={'ordering': ('name',), 'verbose_name': 'insurance category', 'verbose_name_plural': 'insurance categories'},
        ),
        migrations.AlterModelOptions(
            name='insuranceproductresponse',
            options={'ordering': ('-created_at',), 'verbose_name': 'insurance product response', 'verbose_name_plural': 'insurance product responses'},
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='percent_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='rate %'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='term',
            field=models.CharField(choices=[('MO', 'month'), ('YE', 'year')], max_length=2, verbose_name='term'),
        ),
    ]
